import { writeFile } from "node:fs/promises"
import { join } from "node:path"
import { createApp } from "../src/app.ts"
import type { AppConfig } from "../src/config.ts"
import type { Database } from "../src/shared/database.ts"
import { toDiagnosisResponse } from "../src/verification/api/verification.response.ts"
import {
  type Challenge,
  DIAGNOSIS_CODES,
  type Diagnosis,
} from "../src/verification/domain/diagnosis.ts"

export const DOCS_DIRECTORY = join(import.meta.dir, "../../docs")

export const OPENAPI_PATH = join(DOCS_DIRECTORY, "api-reference/openapi.json")
export const DIAGNOSTICS_PATH = join(DOCS_DIRECTORY, "diagnostics/catalogue.mdx")

const DOCUMENTED: AppConfig = {
  port: 0,
  appUrl: "https://ownsi.dev",
  databaseUrl: "postgresql://unused",
  auth: {
    secret: "documentation-secret",
    baseUrl: "https://ownsi.dev",
    basePath: "/api/auth",
    magicLinkTtlSeconds: 600,
    google: null,
  },
  mailer: { driver: "log", apiKey: "", from: "ownsi <no-reply@ownsi.dev>" },
  inngest: {
    driver: "manual",
    id: "ownsi",
    isDev: true,
    baseUrl: null,
    eventKey: "",
    signingKey: "",
  },
  zones: {
    driver: "fake",
    recursiveResolvers: [],
    resolverTimeoutMs: 4_000,
    zoneCacheTtlSeconds: 300,
    soaBudgetMs: 2_500,
  },
  verification: {
    driver: "fake",
    recursiveResolvers: [],
    resolverTimeoutMs: 4_000,
    authoritativeBudgetMs: 2_500,
  },
}

export async function openApiDocument(): Promise<string> {
  const app = createApp(DOCUMENTED, { database: {} as Database })
  const response = await app.handle(new Request("https://ownsi.dev/openapi/json"))
  return `${JSON.stringify(await response.json(), null, 2)}\n`
}

export const CHALLENGE: Challenge = {
  domain: "acme.com",
  token: "ownsi_v1_9f3a2c8d1e4b7a6053c21f8e4d7b0a95",
}

export const SAMPLES: Readonly<Record<(typeof DIAGNOSIS_CODES)[number], Diagnosis>> = {
  domain_appended: {
    code: "domain_appended",
    observed: { name: "_ownsi-challenge.acme.com.acme.com" },
  },
  record_at_apex: {
    code: "record_at_apex",
    observed: { name: "acme.com", value: CHALLENGE.token },
  },
  foreign_token: {
    code: "foreign_token",
    observed: { value: "ownsi_v1_1c05de77a4b83f2690ab4e1d6c7f8352" },
  },
  expired_token: {
    code: "expired_token",
    observed: { value: "ownsi_v1_4c07e9a2d61b83f5029ae7c4b1d6083f" },
  },
  value_formatted: { code: "value_formatted", observed: { value: `"${CHALLENGE.token}"` } },
  no_matching_record: {
    code: "no_matching_record",
    observed: { values: ["v=spf1 include:_spf.google.com ~all", "google-site-verification=aB3"] },
  },
  cname_conflict: { code: "cname_conflict", observed: { target: "acme.pages.dev" } },
  record_absent: { code: "record_absent", observed: { answer: { type: "nxdomain" } } },
  record_on_www: {
    code: "record_on_www",
    observed: { name: "_ownsi-challenge.www.acme.com", value: CHALLENGE.token },
  },
  not_published: {
    code: "not_published",
    observed: { nameservers: ["dana.ns.cloudflare.com", "rick.ns.cloudflare.com"] },
  },
  negative_cache: { code: "negative_cache", observed: { secondsRemaining: 240 } },
  servfail: { code: "servfail", observed: { resolvers: ["cloudflare", "quad9"] } },
  lame_delegation: {
    code: "lame_delegation",
    observed: { nameservers: ["ns1.oldhost.example", "ns2.oldhost.example"] },
  },
}

const PREAMBLE = `---
title: "Diagnostics catalogue"
description: "Every reason a check can fail to find your record, with the cause and the fix ownsi shows you."
icon: "stethoscope"
---

{/* Generated by \`bun run docs:emit\` in apps/api. The copy lives in
apps/api/src/verification/domain/diagnosis.ts — edit it there and regenerate. */}

A check that does not find the token never stops at "not verified". It names one of the thirteen
codes below, and the \`cause\` and \`fix\` sentences on this page are the exact strings the API
returns in \`diagnosis\` — they are generated from the same function the product renders.

Every claim on this page is diagnosed against \`${CHALLENGE.domain}\`, whose token is
\`${CHALLENGE.token}\`. Yours will read your own domain and your own token.
`

export function diagnosticsCatalogue(): string {
  const sections = DIAGNOSIS_CODES.map((code) => section(SAMPLES[code]))
  return `${PREAMBLE}\n${sections.join("\n")}`
}

function section(diagnosis: Diagnosis): string {
  const payload = toDiagnosisResponse(diagnosis, CHALLENGE)

  return [
    `## ${payload.code}`,
    "",
    payload.cause,
    "",
    `**What to do.** ${payload.fix}`,
    "",
    "```json",
    JSON.stringify(payload, null, 2),
    "```",
    "",
  ].join("\n")
}

if (import.meta.main) {
  await writeFile(OPENAPI_PATH, await openApiDocument())
  await writeFile(DIAGNOSTICS_PATH, diagnosticsCatalogue())
  console.log(`wrote ${OPENAPI_PATH}`)
  console.log(`wrote ${DIAGNOSTICS_PATH}`)
}
